### ISSUE TITLE
How to solve this problem

### ISSUE THREAD

**Issue by LiSunny** [redsun/build_x264#1]
make: **\* [.depend] Error 1
Installed: install/arm64
Combining library ......
./build_x264.sh: line 54: cd: install: No such file or directory
fatal error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/lipo: can't open input file: armv7/lib/libx264.a (No such file or directory)
cp: arm64/include/_._: No such file or directory

---

fatal error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/lipo: can't open input file: iPhoneOS/lib/libx264.a (No such file or directory)

**Comment by redsun** [comment]
Compile failed, so did not create the directory， need some details like terminal output .
